### ISSUE TITLE
Dark Theme for IDE (Sidebar & Toolbar)

### ISSUE THREAD

**Issue by sparkyspider** [windflow-io/EternalEngine#17]
For the toolbar and sidebar, should we create custom non-tailwind classes and inject the stylesheet based on the theme, kin of like:

*light.css*
```css
.windflow-bg-colour {
  background-color: #ccc
}
```
*dark.css*
```css
.windflow-bg-colour {
  background-color: #111
}
```

I know you would ideally love everything built in tailwind (custom builds) but I personally thing it's okay to mix in your own mission-specific utility classes (like for theming for example).

Would be nice to test.

Alternatively we could just change a class in the body and have only one stylesheet that we don't swap.

*themes.css*
```css
body.light ** .windflow-bg-colour {
  background-color: #ccc
}
body.dark ** .windflow-bg-colour {
  background-color: #111
}
```
